=== pkrysiak/xml-lab-1/iTunes System/iTunesDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % idAttribute "id ID #REQUIRED">
<!ELEMENT iTunes (Users, Tracks, Playlists) >

<!ELEMENT Users (User+) >
<!ELEMENT User (Name, Surname, DateBirth, Age, Sex, Country)>
<!ATTLIST User %idAttribute;>
<!ATTLIST User password CDATA #REQUIRED >
<!ELEMENT Name (#PCDATA) >
<!ELEMENT Surname (#PCDATA) >
<!ELEMENT DateBirth (#PCDATA) >
<!ELEMENT Age (#PCDATA) >
<!ELEMENT Sex (#PCDATA) >
<!ELEMENT Country (#PCDATA) >

<!ELEMENT Tracks (Track+) >
<!ELEMENT Track (Album, Genre, Duration)>
<!ATTLIST Track %idAttribute;>
<!ATTLIST Track title CDATA #REQUIRED >
<!ATTLIST Track artist CDATA #REQUIRED >
<!ELEMENT Album (#PCDATA) >
<!ELEMENT Genre (#PCDATA) >
<!ELEMENT Duration (#PCDATA) >

<!ELEMENT Playlists (Playlist+)>
<!ELEMENT Playlist (PlTracks) >
<!ATTLIST Playlist %idAttribute;>
<!ELEMENT PlTracks (PlTrack+) >
<!ELEMENT PlTrack (#PCDATA) >
<!ATTLIST PlTrack %idAttribute; >
<!ATTLIST PlTrack title CDATA #REQUIRED >
<!ATTLIST PlTrack year CDATA #REQUIRED >

=== pkrysiak/xml-lab-1/iTunes System/itunes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iTunes SYSTEM "iTunesDTD.dtd">
<iTunes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="iTunesSchema.xsd">
    <Users>
        <User id ="j.silver" password="asfasf">
            <Name>Jonas</Name>
            <Surname>Silver</Surname>
            <DateBirth>1990-08-23</DateBirth>
            <Age>24</Age>
            <Sex>Male</Sex>
            <Country>Canada</Country>
        </User>
        <User id = "m.anne" password="hrs362h">
            <Name>Mary</Name>
            <Surname>Anne</Surname>
            <DateBirth>1989-03-14</DateBirth>
            <Age>25</Age>
            <Sex>Female</Sex>
            <Country>France</Country>
        </User>
        <User id = "d.fisher" password="sgsg242">
            <Name>Derek</Name>
            <Surname>Fisher</Surname>
            <DateBirth>1987-06-16</DateBirth>
            <Age>27</Age>
            <Sex>Male</Sex>
            <Country>U.S.A.</Country>
        </User>
    </Users>
    <Tracks>
        <Track id = "t97124" title = "Get Lucky (feat. Pharrell)" artist = "Daft Punk">
            <Album>Random Access Memories</Album>
            <Genre>Funk</Genre>
            <Duration>4:08</Duration>
        </Track>
        <Track id = "t26532" title = "Attak (feat. Danny Brown)" artist = "Rustie">
            <Album>Green Language</Album>
            <Genre>Electronic</Genre>
            <Duration>3:01</Duration>
        </Track>
        <Track id = "t15225" title = "Feels Like We Only Go Backwards" artist = "Tame Impala">
            <Album>Lonerism</Album>
            <Genre>Rock</Genre>
            <Duration>3:12</Duration>
        </Track>
        <Track id = "t58684" title = "Swimming Pools (Drank)" artist = "Kendrick Lamar">
            <Album>Good Kid, Mad City</Album>
            <Genre>Rap</Genre>
            <Duration>5:13</Duration>
        </Track>
        <Track id = "t25132" title = "Blood On The Leaves" artist = "Kanye West">
            <Album>Yeezus</Album>
            <Genre>Rap</Genre>
            <Duration>6:00</Duration>
        </Track>
    </Tracks>
    <Playlists>
        <Playlist id = "pl32535">
            <PlTracks>
                <PlTrack pltid = "t97124" title = "Get Lucky (feat. Pharrell)" year = "2013"/>
                <PlTrack pltid = "t26532" title = "Attak (feat. Danny Brown)" year = "2014"/>
                <PlTrack pltid = "t15225" title = "Feels Like We Only Go Backwards" year = "2012"/>
                <PlTrack pltid = "t58684" title = "Swimming Pools (Drank)" year = "2012"/>
                <PlTrack pltid = "t25132" title = "Blood On The Leaves" year = "2013"/>
            </PlTracks>
        </Playlist>
    </Playlists>
</iTunes>
