=== pkrysiak/xml-lab-1/teams (with search parameter)/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://ssdi.di.fct.unl.pt/ctxml/soccerLeague" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:xxl="http://ssdi.di.fct.unl.pt/ctxml/soccerLeague"
    targetNamespace="http://ssdi.di.fct.unl.pt/ctxml/soccerLeague" elementFormDefault="qualified" >
    <xs:annotation>
        <xs:appinfo>CTXML Lab 1</xs:appinfo>
        <xs:documentation xml:lang="en">
            Authors: Bruno Palma | No. 42003
            Pawel Krysiak | No. 44778
            XML Schema for SocccerLeague
        </xs:documentation>
    </xs:annotation>
    <xs:element name="soccerLeague">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="players">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="player" minOccurs ="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nick" type="xs:string"></xs:element>
                                        <xs:element name="nationality" type="xs:string"></xs:element>
                                        <xs:element name="birthDate" type="xs:date"></xs:element>
                                        <xs:element name="awards">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="award" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="playedClubs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="playedClub" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="clubref" type="xs:NCName" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:NCName" use="required"/>
                                    <xs:attribute name="position" type="playersPositions" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="playerID"> 
                        <xs:selector xpath="xxl:player"/> 
                        <xs:field xpath="@id"/> 
                    </xs:key>
                </xs:element>
                <xs:element name="clubs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="club" minOccurs ="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="acronym" type="xs:string"></xs:element>
                                        <xs:element name="city" type="xs:string"></xs:element>
                                        <xs:element name="stadium" type="xs:string"></xs:element>
                                        
                                        <xs:element name="ranks">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="rank" maxOccurs="unbounded" >
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:integer">
                                                                    <xs:attribute name="year" type="xs:string" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>                                                    
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string"></xs:element>
                                        <xs:element name="webLink" type="xs:string"></xs:element>
                                        <xs:element name="teamPlayers">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="teamPlayer" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="playedPosition" type="playersPositions" use="required"/>
                                                                    <xs:attribute name="id" type="xs:NCName" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>                                                            
                                                        </xs:complexType>                                                        
                                                    </xs:element>
                                                </xs:sequence>                                                
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:NCName" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="clubID">
                        <xs:selector xpath="xxl:club"/>
                        <xs:field xpath="@id"/>
                    </xs:key>
                </xs:element>                
                <xs:element name="games">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="game" minOccurs ="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="location" type="xs:string"></xs:element>
                                        <xs:element name="spectatorsNumber" type="xs:integer"></xs:element>
                                        <xs:element name="result">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="goals" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:integer">
                                                                    <xs:attribute name="clubId" type="xs:NCName" use="required"></xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="initialPlayers">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="initialPlayer"  minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="playerId" type="xs:NCName" use="required"/>
                                                            <xs:attribute name="plClubId" type="xs:NCName" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="substitutions">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="substitution" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="playerId" type="xs:NCName" use="required"/>
                                                            <xs:attribute name="substitutedPlayerId" type="xs:NCName" use="required"/>
                                                            <xs:attribute name="clubId" type="xs:NCName" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="scoringPlayers">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="scoringPlayer" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="playerId" type="xs:NCName" use="required"/>
                                                            <xs:attribute name="clubId" type="xs:NCName" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:NCName" use="required"/>
                                    <xs:attribute name="firstTeam" type="xs:NCName" use="required"/>
                                    <xs:attribute name="secondTeam" type="xs:NCName" use="required"/>
                                    <xs:attribute name="week" type="xs:NCName" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="gameID">
                        <xs:selector xpath="xxl:game"/>
                        <xs:field xpath="@id"/>
                    </xs:key>
                </xs:element>
                <xs:element name="stats"></xs:element>            
            </xs:sequence> 
            <xs:attribute name="id" type="xs:NCName" use="required"/>
        </xs:complexType>
        
        <xs:key name="leagueID"> 
            <xs:selector xpath="."/> 
            <xs:field xpath="@id"/> 
        </xs:key>
        
        <xs:keyref name="playerRef" refer="xxl:playerID">
            <xs:selector xpath="./xxl:clubs/xxl:club/xxl:teamPlayers/xxl:teamPlayer"/> 
            <xs:field xpath="@id"/> 
        </xs:keyref>
        
        <xs:keyref name="initialPlayerRef" refer="playerID"> 
            <xs:selector xpath="./xxl:games/xxl:game/xxl:initialPlayers/xxl:initialPlayer"/> 
            <xs:field xpath="@playerId"/> 
        </xs:keyref>
        
        <!-- substitution -->
        
        <xs:keyref name="substitutionPlayerRef" refer="playerID"> 
            <xs:selector xpath="./xxl:games/xxl:game/xxl:substitutions/xxl:substitution"/> 
            <xs:field xpath="@playerId"/> 
        </xs:keyref>
        
        <xs:keyref name="substitutionPlayerRef1" refer="playerID"> 
            <xs:selector xpath="./xxl:games/xxl:game/xxl:substitutions/xxl:substitution"/> 
            <xs:field xpath="@substitutedPlayerId"/> 
        </xs:keyref>
        
        <xs:keyref name="subClId" refer="clubID"> 
            <xs:selector xpath="./xxl:games/xxl:game/xxl:substitutions/xxl:substitution"/> 
            <xs:field xpath="@clubId"/> 
        </xs:keyref>
        
        <!-- scoringPlayer -->
        <xs:keyref name="scoringPlayerRef" refer="playerID"> 
            <xs:selector xpath="./xxl:games/xxl:game/xxl:scoringPlayers/xxl:scoringPlayer"/> 
            <xs:field xpath="@playerId"/> 
        </xs:keyref>
        
        <xs:keyref name="scoringClubRef" refer="clubID"> 
            <xs:selector xpath="./xxl:games/xxl:game/xxl:scoringPlayers/xxl:scoringPlayer"/> 
            <xs:field xpath="@clubId"/> 
        </xs:keyref>
        
        <!-- goals -->
        
        <xs:keyref name="goalsClubRef" refer="clubID"> 
            <xs:selector xpath="./xxl:games/xxl:game/xxl:result/xxl:goals"/> 
            <xs:field xpath="@clubId"/> 
        </xs:keyref>
    </xs:element>    
    
    
    <xs:simpleType name="playersPositions">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Medio" />
            <xs:enumeration value="Defesa" />
            <xs:enumeration value="GuardaRedes" />
            <xs:enumeration value="Avancado" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== pkrysiak/xml-lab-1/stadiums/index.xml
<?xml version="1.0" encoding="UTF-8"?>

<soccerLeague xmlns="http://ssdi.di.fct.unl.pt/ctxml/soccerLeague" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ssdi.di.fct.unl.pt/ctxml/soccerLeague schema.xsd" id="SagresLeague1415">
    <players>
        <player id="Artur" position="GuardaRedes">
            <nick>Artur</nick>
            <nationality>Brasil</nationality>
            <birthDate>1981-01-25</birthDate>
            <awards>
                <award>award1</award>
                <award>award2</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="Luisao" position="Defesa">
            <nick>Luisao</nick>
            <nationality>Brasil</nationality>
            <birthDate>1981-02-13</birthDate>
            <awards>
                <award>award3</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="Samaris" position="Medio">
            <nick>Samaris</nick>
            <nationality>Grecia</nationality>
            <birthDate>1989-06-13</birthDate>
            <awards></awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="N.Gaitan" position="Medio">
            <nick>Gaitan</nick>
            <nationality>Argentina</nationality>
            <birthDate>1988-02-23</birthDate>
            <awards>
                <award>award4</award>
                <award>award5</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="Lima" position="Defesa">
            <nick>Lima</nick>
            <nationality>Brasil</nationality>
            <birthDate>1983-05-11</birthDate>
            <awards>
                <award>award6</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="Maxi" position="Defesa">
            <nick>Maxi</nick>
            <nationality>Uruguay</nationality>
            <birthDate>1984-06-08</birthDate>
            <awards>
                <award>award22</award>
                <award>award23</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="Salvio" position="Defesa">
            <nick>Salvio</nick>
            <nationality>Portugal</nationality>
            <birthDate>1987-09-28</birthDate>
            <awards>
                <award>award22</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="Eliseu" position="Defesa">
            <nick>Eliseu</nick>
            <nationality>Portugal</nationality>
            <birthDate>1983-10-01</birthDate>
            <awards>
                <award>award22</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="A.Talisca" position="Avancado">
            <nick>A.Talisca</nick>
            <nationality>Brasil</nationality>
            <birthDate>1994-02-01</birthDate>
            <awards>
                <award>award22</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="Jardel" position="Defesa">
            <nick>Jardel</nick>
            <nationality>Brasil</nationality>
            <birthDate>1986-03-29</birthDate>
            <awards>
                <award>award22</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="Perez" position="Medio">
            <nick>Perez</nick>
            <nationality>Argentina</nationality>
            <birthDate>1986-02-22</birthDate>
            <awards>
                <award>award22</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Benfica"/>
            </playedClubs>
        </player>
        <player id="R.Patricio" position="GuardaRedes">
            <nick>Patricio</nick>
            <nationality>Portugal</nationality>
            <birthDate>1988-02-15</birthDate>
            <awards>
                <award>award7</award>
                <award>award8</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="Jefferson" position="Defesa">
            <nick>Jefferson</nick>
            <nationality>Brasil</nationality>
            <birthDate>1988-07-05</birthDate>
            <awards>
                <award>award9</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="A.Martins" position="Medio">
            <nick>Martins</nick>
            <nationality>Portugal</nationality>
            <birthDate>1990-01-21</birthDate>
            <awards></awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>        
        <player id="Slimani" position="Avancado">
            <nick>Slimani</nick>
            <nationality>Algeria</nationality>
            <birthDate>1988-06-18</birthDate>
            <awards>
                <award>award10</award>
                <award>award11</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="William" position="Avancado">
            <nick>William</nick>
            <nationality>Angola</nationality>
            <birthDate>1992-04-07</birthDate>
            <awards>
                <award>award12</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="Nani" position="Avancado">
            <nick>Nani</nick>
            <nationality>Portugal</nationality>
            <birthDate>1986-11-17</birthDate>
            <awards>
                <award>award22</award>
                <award>award23</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="Cedric" position="Defesa">
            <nick>Cedric</nick>
            <nationality>Portugal</nationality>
            <birthDate>1991-08-31</birthDate>
            <awards>
                <award>award22</award>
                <award>award23</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="N.Sarr" position="Defesa">
            <nick>N.Sarr</nick>
            <nationality>Fran√ßa</nationality>
            <birthDate>1992-08-13</birthDate>
            <awards>
                <award>award22</award>
                <award>award23</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="P.Oliveira" position="Defesa">
            <nick>P.Oliveira</nick>
            <nationality>Portugal</nationality>
            <birthDate>1992-01-08</birthDate>
            <awards>
                <award>award22</award>
                <award>award23</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="J.Mario" position="Medio">
            <nick>J.Mario</nick>
            <nationality>Portugal</nationality>
            <birthDate>1993-01-19</birthDate>
            <awards>
                <award>award22</award>
                <award>award23</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <player id="CarriloD." position="Avancado">
            <nick>CarriloD.</nick>
            <nationality>Peru</nationality>
            <birthDate>1991-06-14</birthDate>
            <awards>
                <award>award22</award>
                <award>award23</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Sporting"/>
            </playedClubs>
        </player>
        <!-- Estoril -->
        <!-- Estoril -->
        
        <player id="Matias" position="Medio">
            <nick>Matias</nick>
            <nationality>Uruguai</nationality>
            <birthDate>1986-05-16</birthDate>
            <awards>
                <award>award13</award>
                <award>award14</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Estoril"/>
            </playedClubs>
        </player>
        <player id="Baltazar" position="Medio">
            <nick>Baltazar</nick>
            <nationality>Portugal</nationality>
            <birthDate>1995-04-15</birthDate>
            <awards>
                <award>award15</award>
            </awards>
            <playedClubs>
                <playedClub clubref="Estoril"/>
            </playedClubs>
        </player>
        <player id="J.Miranda" position="Avancado">
            <nick>Miranda</nick>
            <nationality>Cabo Verde</nationality>
            <birthDate>1989-08-02</birthDate>
            <awards></awards>
            <playedClubs>
                <playedClub clubref="Estoril"/>
